# -*- coding: utf-8 -*-
"""Benz: Pytorch | MLflow | Sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmgCjhPjlVBnCrYC0nXR-LajBK2xxU4J

<p align="center">
    <img src="https://malikkhubiev.github.io/benz/merscedes.png" width="1000"/>
</p>

# Mercedes-Benz Price Intelligence
### Мульти-модельный подход с MLflow и PyTorch

## #1. Установка и импорт библиотек
"""

# Установка библиотек
!pip install mlflow pytorch-tabnet xgboost catboost --quiet

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Models
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
import xgboost as xgb
import catboost as cb

# PyTorch
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Preprocessing & Metrics
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# MLflow
import mlflow
import mlflow.sklearn
import mlflow.pytorch

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

print(f"PyTorch version: {torch.__version__}")
print(f"MLflow version: {mlflow.__version__}")

"""## #2. Загрузка и первичный анализ данных"""

# Загрузка данных с правильными названиями колонок
import pandas as pd
import numpy as np
import re

df = pd.read_csv('clean_mers.csv')

# Переименование колонок для удобства работы
df.columns = ['full_name', 'price', 'details', 'rating']

print(f"Исходный размер датасета: {df.shape}")
print("\nПервые 5 строк:")
print(df.head())
print("\nКолонки:", df.columns.tolist())

# Функция для очистки цены от всех видов пробелов и символов
def clean_price(price_str):
    """
    Очищает строку цены от символов валюты и пробелов
    Пример: "1 050 000 ₽" -> 1050000
    """
    if pd.isna(price_str):
        return 0

    # Убрать символ рубля
    price_str = str(price_str).replace('₽', '')
    # Убрать все виды пробелов (обычные, неразрывные и т.д.)
    price_str = re.sub(r'\s+', '', price_str).replace('\xa0', '')
    # Если после очистки осталась пустая строка
    if not price_str:
        return 0
    # Конвертируем в int
    return int(price_str)

# Применение очистки цены
df['price'] = df['price'].apply(clean_price)

# Извлечение информации из full_name
def parse_full_name(full_name):
    """
    Парсинг строки вида: "Mercedes-Benz C-класс 1.6 AT, 2019, 97 000 км"
    """
    if pd.isna(full_name):
        return pd.Series({'model': 'Unknown', 'year': 0, 'mileage': 0})

    # Разделение по запятой
    parts = full_name.split(',')

    # Если недостаточно частей, возвращение значения по умолчанию
    if len(parts) < 3:
        return pd.Series({'model': full_name[:50], 'year': 0, 'mileage': 0})

    # Первая часть содержит модель и комплектацию
    model_part = parts[0].strip()

    # Извлечение модели (Mercedes-Benz X-класс)
    # Поиск паттерна "Mercedes-Benz" + слово с дефисом или без
    model_match = re.search(r'(Mercedes-Benz[\w\-\s]+?)(?=\s\d|$)', model_part)
    if model_match:
        model = model_match.group(1).strip()
    else:
        # Если не нашли, берем первые слова до цифры
        words = []
        for word in model_part.split():
            if any(c.isdigit() for c in word):
                break
            words.append(word)
        model = ' '.join(words) if words else model_part[:30]

    # Извлечение года
    try:
        year = int(parts[1].strip())
    except:
        year = 0

    # Извлечение пробега
    try:
        mileage_str = parts[2].strip()
        # Удаление всех не-цифровых символов
        mileage_str = re.sub(r'[^\d]', '', mileage_str)
        mileage = int(mileage_str) if mileage_str else 0
    except:
        mileage = 0

    return pd.Series({
        'model': model,
        'year': year,
        'mileage': mileage
    })

# Применение парсинга
parsed_data = df['full_name'].apply(parse_full_name)
df[['model', 'year', 'mileage']] = parsed_data

# Расчёт возраста автомобиля
current_year = 2026
df['age'] = current_year - df['year']

# Удаление строки с некорректными данными
df = df[df['year'] > 1900].copy()  # Год должен быть разумным
df = df[df['price'] > 0].copy()     # Цена должна быть положительной

# Удаление выбросов по цене (очень дорогие или дешевые)
df = df[(df['price'] >= 100000) & (df['price'] < 40000000)].copy()
print(f"\nРазмер после очистки: {df.shape}")

# Проверка на пропуски
print("\nПропуски в данных:")
print(df.isnull().sum())

# Базовые статистики
print("\nСтатистика по цене:")
print(df['price'].describe([0.1, 0.25, 0.5, 0.75, 0.9]).apply(lambda x: f'{x:,.0f}'))

print("\nСтатистика по пробегу:")
print(df['mileage'].describe([0.1, 0.25, 0.5, 0.75, 0.9]).apply(lambda x: f'{x:,.0f}'))

print("\nСтатистика по году:")
print(df['year'].describe())

print("\nРаспределение по моделям:")
print(df['model'].value_counts().head(10))

print("\nДиапазон годов выпуска:")
print(f"От {df['year'].min()} до {df['year'].max()}")

# Отображение нескольких примеров очищенных данных
print("\nПримеры очищенных данных:")
print(df[['full_name', 'model', 'year', 'mileage', 'price', 'age']].head(10).to_string())

# Проверка проблемных строк, которые могли быть отфильтрованы
print("\nСтатистика по исходным данным:")
print(f"Всего строк в исходном файле: {len(df)}")
print(f"Строк с годом > 1900: {(df['year'] > 1900).sum()}")
print(f"Строк с ценой > 0: {(df['price'] > 0).sum()}")

"""## #3. Продвинутая инженерия признаков"""

# Копия датафрейма для работы
df_feat = df.copy()

# 1. Признаки на основе модели
model_stats = df_feat.groupby('model')['price'].agg(['mean', 'median', 'std', 'count'])
model_stats.columns = ['model_price_mean', 'model_price_median', 'model_price_std', 'model_count']
model_stats = model_stats.fillna(0)
df_feat = df_feat.merge(model_stats, on='model', how='left')

# Для моделей с одним объявлением std будет NaN, заполнение 0
df_feat['model_price_std'] = df_feat['model_price_std'].fillna(0)

# 2. Логарифмические преобразования (добавление 1 чтобы избежать log(0))
df_feat['log_price'] = np.log1p(df_feat['price'])
df_feat['log_mileage'] = np.log1p(df_feat['mileage'])
df_feat['log_model_price_mean'] = np.log1p(df_feat['model_price_mean'])

# 3. Полиномиальные признаки (взаимодействия)
df_feat['mileage_per_year'] = df_feat['mileage'] / (df_feat['age'] + 1)
df_feat['price_per_year'] = df_feat['price'] / (df_feat['age'] + 1)
df_feat['mileage_x_age'] = df_feat['mileage'] * df_feat['age']

# 4. Бинарные признаки
df_feat['is_new'] = (df_feat['age'] <= 3).astype(int)  # Машины до 3 лет считаются новыми
df_feat['is_almost_new'] = ((df_feat['age'] > 3) & (df_feat['age'] <= 7)).astype(int)
df_feat['high_mileage'] = (df_feat['mileage'] > 150000).astype(int)
df_feat['very_high_mileage'] = (df_feat['mileage'] > 300000).astype(int)
df_feat['is_premium'] = (df_feat['model_price_mean'] > df_feat['model_price_mean'].median()).astype(int)

# 5. Признаки популярности модели
df_feat['model_popularity'] = df_feat['model_count'] / len(df_feat)

# 6. Ценовые сегменты (категориальный признак)
price_bins = [0, 1e6, 2e6, 3e6, 5e6, 10e6, 40e6]
price_labels = ['Economy', 'Budget', 'Mid', 'Premium', 'Luxury', 'Ultra-Luxury']
df_feat['price_segment'] = pd.cut(df_feat['price'], bins=price_bins, labels=price_labels)

# One-hot encoding для ценового сегмента (если нужно)
segment_dummies = pd.get_dummies(df_feat['price_segment'], prefix='segment')
df_feat = pd.concat([df_feat, segment_dummies], axis=1)

# 7. Признаки на основе года выпуска
df_feat['year_rank'] = current_year - df_feat['year']
df_feat['decade'] = (df_feat['year'] // 10) * 10

# One-hot encoding для декады
decade_dummies = pd.get_dummies(df_feat['decade'], prefix='decade')
df_feat = pd.concat([df_feat, decade_dummies], axis=1)

# 8. Целевая переменная
target = 'log_price'

print("Новые признаки созданы.")
print(f"Размерность после инженерии: {df_feat.shape}")
print(f"Количество признаков: {len(df_feat.columns)}")

print("\nТоп-10 новых колонок (первые 10 из множества):")
new_cols = sorted(list(set(df_feat.columns) - set(df.columns)))
print(new_cols[:10])
print(f"... и еще {len(new_cols) - 10} колонок")

# Проверка корреляцию новых признаков с ценой
print("\nКорреляция новых признаков с ценой (топ-10):")
numeric_cols = df_feat.select_dtypes(include=[np.number]).columns
correlations = df_feat[numeric_cols].corr()['price'].sort_values(ascending=False)
print(correlations.head(11))  # 11 потому что первый это сама price

"""## #4. Отбор признаков и подготовка данных"""

from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
import torch

# Определение финального список признаков
feature_cols = [
    # Исходные числовые
    'year', 'age',

    # Признаки на основе модели
    'model_price_mean', 'model_price_median', 'model_price_std', 'model_popularity',

    # Логарифмические
    'log_mileage', 'log_model_price_mean',

    # Полиномиальные
    'mileage_per_year', 'price_per_year', 'mileage_x_age',

    # Бинарные
    'is_new', 'is_almost_new', 'high_mileage', 'very_high_mileage', 'is_premium',

    # Годовые признаки
    'year_rank'
]

# Добавление one-hot encoded признаков для декад и сегментов (выборочно)
decade_cols = [col for col in df_feat.columns if col.startswith('decade_')]
segment_cols = [col for col in df_feat.columns if col.startswith('segment_')]

# Добавление только релевантных декад и сегментов (где есть данные)
for col in decade_cols + segment_cols:
    if df_feat[col].sum() > 0:  # Только если есть хотя бы одно вхождение
        feature_cols.append(col)

# Проверка, что все признаки существуют
existing_features = [f for f in feature_cols if f in df_feat.columns]
print(f"Используем {len(existing_features)} признаков")
print("\nПервые 20 признаков:")
print(existing_features[:20])

# Проверка на наличие NaN
X = df_feat[existing_features]
y = df_feat[target]

print(f"\nПроверка на NaN в X: {X.isnull().sum().sum()}")
if X.isnull().sum().sum() > 0:
    print("Заполняем NaN средними значениями...")
    X = X.fillna(X.mean())

print(f"Проверка на NaN в y: {y.isnull().sum()}")

# Разделение на train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Масштабирование (для моделей, которым это нужно)
scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Тензоры для PyTorch
X_train_tensor = torch.FloatTensor(X_train_scaled)
y_train_tensor = torch.FloatTensor(y_train.values).view(-1, 1)
X_test_tensor = torch.FloatTensor(X_test_scaled)
y_test_tensor = torch.FloatTensor(y_test.values).view(-1, 1)

print(f"\nTrain set: {X_train.shape}")
print(f"Test set: {X_test.shape}")
print(f"Диапазон цен в train: {np.expm1(y_train).min():,.0f} - {np.expm1(y_train).max():,.0f} руб")
print(f"Диапазон цен в test: {np.expm1(y_test).min():,.0f} - {np.expm1(y_test).max():,.0f} руб")

"""## #5. Настройка MLflow"""

# Установка эксперимента в MLflow
EXPERIMENT_NAME = "Mercedes-Benz Price Prediction"

# Попытка создать эксперимент, если он не существует
try:
    experiment_id = mlflow.create_experiment(
        name=EXPERIMENT_NAME,
        artifact_location="./mlruns"  # локальное хранилище артефактов
    )
    print(f"Создан новый эксперимент: {EXPERIMENT_NAME} (ID: {experiment_id})")
except:
    experiment = mlflow.get_experiment_by_name(EXPERIMENT_NAME)
    experiment_id = experiment.experiment_id
    print(f"Используем существующий эксперимент: {EXPERIMENT_NAME} (ID: {experiment_id})")

mlflow.set_experiment(EXPERIMENT_NAME)

# Функция для оценки модели в рублях (обратное преобразование из логарифма)
def evaluate_model_rub(y_true_log, y_pred_log):
    y_true_rub = np.expm1(y_true_log)
    y_pred_rub = np.expm1(y_pred_log)

    r2 = r2_score(y_true_rub, y_pred_rub)
    mae = mean_absolute_error(y_true_rub, y_pred_rub)
    rmse = np.sqrt(mean_squared_error(y_true_rub, y_pred_rub))
    mape = np.mean(np.abs((y_true_rub - y_pred_rub) / y_true_rub)) * 100

    return {
        'r2': r2,
        'mae': mae,
        'rmse': rmse,
        'mape': mape
    }

"""## #6. Определение PyTorch модели"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
from sklearn.metrics import r2_score

class ImprovedPricePredictor(nn.Module):
    """
    Улучшенная нейросеть для предсказания цены автомобиля
    Особенности:
    - Residual connections (остаточные связи)
    - LayerNorm вместо BatchNorm (лучше для малых батчей)
    - Адаптивная скорость обучения
    - L2 регуляризация (weight decay)
    - Градиентный клиппинг
    """
    def __init__(self, input_dim, hidden_dims=[256, 128, 64, 32], dropout_rate=0.1):
        super(ImprovedPricePredictor, self).__init__()

        self.input_dim = input_dim

        # Входной слой
        self.input_layer = nn.Sequential(
            nn.Linear(input_dim, hidden_dims[0]),
            nn.LayerNorm(hidden_dims[0]),
            nn.ReLU(),
            nn.Dropout(dropout_rate)
        )

        # Скрытые слои с residual connections
        self.hidden_layers = nn.ModuleList()
        self.residual_connections = nn.ModuleList()

        for i in range(len(hidden_dims) - 1):
            in_dim = hidden_dims[i]
            out_dim = hidden_dims[i + 1]

            # Основной слой
            self.hidden_layers.append(nn.Sequential(
                nn.Linear(in_dim, out_dim),
                nn.LayerNorm(out_dim),
                nn.ReLU(),
                nn.Dropout(dropout_rate)
            ))

            # Residual connection (если размерности совпадают)
            if in_dim == out_dim:
                self.residual_connections.append(nn.Identity())
            else:
                self.residual_connections.append(nn.Linear(in_dim, out_dim))

        # Выходной слой
        self.output_layer = nn.Linear(hidden_dims[-1], 1)

        # Инициализация весов (Xavier/Glorot)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            nn.init.xavier_uniform_(module.weight)
            if module.bias is not None:
                nn.init.constant_(module.bias, 0)

    def forward(self, x):
        # Входной слой
        x = self.input_layer(x)

        # Скрытые слои с residual connections
        for i, layer in enumerate(self.hidden_layers):
            residual = self.residual_connections[i](x)
            x = layer(x)
            x = x + residual  # Residual connection

        # Выход
        x = self.output_layer(x)
        return x


class PriceDataset(torch.utils.data.Dataset):
    """Кастомный датасет с нормализацией"""
    def __init__(self, X, y):
        self.X = torch.FloatTensor(X)
        self.y = torch.FloatTensor(y.values if hasattr(y, 'values') else y).view(-1, 1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


def train_pytorch_model(
    model,
    train_loader,
    test_loader,
    criterion,
    optimizer,
    scheduler,
    epochs=1000,
    patience=100,
    clip_grad_norm=1.0
):
    """
    Улучшенная функция обучения с:
    - Плато scheduler
    - Градиентный клиппинг
    - Сохранение лучшей модели
    - Мониторинг R²
    """
    train_losses = []
    test_losses = []
    train_r2_scores = []
    test_r2_scores = []

    best_test_loss = float('inf')
    best_test_r2 = -float('inf')
    patience_counter = 0
    best_model_state = None

    for epoch in range(epochs):
        # Training
        model.train()
        train_loss = 0
        all_train_preds = []
        all_train_targets = []

        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            output = model(X_batch)
            loss = criterion(output, y_batch)
            loss.backward()

            # Градиентный клиппинг
            torch.nn.utils.clip_grad_norm_(model.parameters(), clip_grad_norm)

            optimizer.step()
            train_loss += loss.item()

            all_train_preds.append(output.detach().numpy())
            all_train_targets.append(y_batch.numpy())

        avg_train_loss = train_loss / len(train_loader)
        train_losses.append(avg_train_loss)

        # R² на train
        train_preds = np.concatenate(all_train_preds).flatten()
        train_targets = np.concatenate(all_train_targets).flatten()
        train_r2 = r2_score(train_targets, train_preds)
        train_r2_scores.append(train_r2)

        # Evaluation
        model.eval()
        test_loss = 0
        all_test_preds = []
        all_test_targets = []

        with torch.no_grad():
            for X_batch, y_batch in test_loader:
                output = model(X_batch)
                loss = criterion(output, y_batch)
                test_loss += loss.item()

                all_test_preds.append(output.numpy())
                all_test_targets.append(y_batch.numpy())

        avg_test_loss = test_loss / len(test_loader)
        test_losses.append(avg_test_loss)

        # R² на test
        test_preds = np.concatenate(all_test_preds).flatten()
        test_targets = np.concatenate(all_test_targets).flatten()
        test_r2 = r2_score(test_targets, test_preds)
        test_r2_scores.append(test_r2)

        # Scheduler step
        if scheduler is not None:
            scheduler.step(avg_test_loss)

        # Early stopping по R²
        if test_r2 > best_test_r2:
            best_test_r2 = test_r2
            best_test_loss = avg_test_loss
            best_model_state = model.state_dict().copy()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"Early stopping at epoch {epoch} (best R² = {best_test_r2:.4f})")
                break

        # Печать прогресса
        if (epoch + 1) % 50 == 0:
            current_lr = optimizer.param_groups[0]['lr']
            print(f'Epoch [{epoch+1}/{epochs}] | '
                  f'Train Loss: {avg_train_loss:.4f} | '
                  f'Test Loss: {avg_test_loss:.4f} | '
                  f'Train R²: {train_r2:.4f} | '
                  f'Test R²: {test_r2:.4f} | '
                  f'LR: {current_lr:.2e}')

    # Load best model
    model.load_state_dict(best_model_state)

    return {
        'train_losses': train_losses,
        'test_losses': test_losses,
        'train_r2': train_r2_scores,
        'test_r2': test_r2_scores,
        'best_test_r2': best_test_r2,
        'best_test_loss': best_test_loss
    }

"""## #7. Запуск экспериментов с MLflow"""

# Словарь для хранения результатов всех моделей
all_results = {}

# Конфигурации моделей для экспериментов
models_config = [
    {
        'name': 'LinearRegression',
        'model': LinearRegression(),
        'use_scaled': True,
        'params': {}
    },
    {
        'name': 'Ridge',
        'model': Ridge(alpha=1.0),
        'use_scaled': True,
        'params': {'alpha': 1.0}
    },
    {
        'name': 'Lasso',
        'model': Lasso(alpha=0.001),
        'use_scaled': True,
        'params': {'alpha': 0.001}
    },
    {
        'name': 'RandomForest',
        'model': RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42),
        'use_scaled': False,
        'params': {'n_estimators': 200, 'max_depth': 10}
    },
    {
        'name': 'GradientBoosting',
        'model': GradientBoostingRegressor(n_estimators=200, max_depth=5, learning_rate=0.1, random_state=42),
        'use_scaled': False,
        'params': {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.1}
    },
    {
        'name': 'XGBoost',
        'model': xgb.XGBRegressor(n_estimators=200, max_depth=5, learning_rate=0.1, random_state=42),
        'use_scaled': False,
        'params': {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.1}
    },
    {
        'name': 'CatBoost',
        'model': cb.CatBoostRegressor(iterations=200, depth=5, learning_rate=0.1, verbose=0, random_seed=42),
        'use_scaled': False,
        'params': {'iterations': 200, 'depth': 5, 'learning_rate': 0.1}
    }
]

# Обучение sklearn-моделей
for config in models_config:
    with mlflow.start_run(run_name=config['name']):
        print(f"\n{'='*50}")
        print(f"Обучение модели: {config['name']}")
        print('='*50)

        # Логирование параметров
        mlflow.log_params(config['params'])
        mlflow.set_tag('model_type', 'sklearn')

        # Отбор данных
        if config['use_scaled']:
            X_tr, X_te = X_train_scaled, X_test_scaled
        else:
            X_tr, X_te = X_train.values, X_test.values

        # Обучение
        model = config['model']
        model.fit(X_tr, y_train)

        # Предсказания
        y_pred_train = model.predict(X_tr)
        y_pred_test = model.predict(X_te)

        # Оценка
        train_metrics = evaluate_model_rub(y_train, y_pred_train)
        test_metrics = evaluate_model_rub(y_test, y_pred_test)

        # Логирование метрик
        mlflow.log_metrics({
            'train_r2': train_metrics['r2'],
            'train_mae': train_metrics['mae'],
            'train_rmse': train_metrics['rmse'],
            'train_mape': train_metrics['mape'],
            'test_r2': test_metrics['r2'],
            'test_mae': test_metrics['mae'],
            'test_rmse': test_metrics['rmse'],
            'test_mape': test_metrics['mape']
        })

        # Сохранение модели
        mlflow.sklearn.log_model(model, config['name'])

        # Вывод результатов
        print(f"\n{config['name']} - Результаты:")
        print(f"  Train R²: {train_metrics['r2']:.4f}, MAPE: {train_metrics['mape']:.2f}%")
        print(f"  Test  R²: {test_metrics['r2']:.4f}, MAPE: {test_metrics['mape']:.2f}%")

        # Сохранение для сравнения
        all_results[config['name']] = test_metrics

"""## #8. Сравнение всех моделей"""

# Создание DataFrame для сравнения
comparison_df = pd.DataFrame(all_results).T
comparison_df = comparison_df.sort_values('r2', ascending=False)

print("\n" + "="*60)
print("СРАВНЕНИЕ ВСЕХ МОДЕЛЕЙ (на тестовых данных)")
print("="*60)
print(comparison_df.round(4).to_string())

# Визуализация сравнения
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# R² сравнение
axes[0].barh(comparison_df.index, comparison_df['r2'])
axes[0].set_xlabel('R² Score')
axes[0].set_title('Сравнение моделей по R²')
axes[0].grid(True, axis='x')

# MAE сравнение
axes[1].barh(comparison_df.index, comparison_df['mae'])
axes[1].set_xlabel('MAE (руб)')
axes[1].set_title('Сравнение моделей по MAE')
axes[1].grid(True, axis='x')

# MAPE сравнение
axes[2].barh(comparison_df.index, comparison_df['mape'])
axes[2].set_xlabel('MAPE (%)')
axes[2].set_title('Сравнение моделей по MAPE')
axes[2].grid(True, axis='x')

plt.tight_layout()
plt.show()

# Сохранение лучшей модели отдельно
best_model_name = comparison_df.index[0]
print(f"\nЛучшая модель: {best_model_name} с R² = {comparison_df.iloc[0]['r2']:.4f}")

"""## #9. Обучение PyTorch модели"""

print("\n" + "="*60)
print("ОБУЧЕНИЕ УЛУЧШЕННОЙ PyTorch МОДЕЛИ")
print("="*60)

# Параметры
params = {
    'hidden_dims': [256, 128, 64, 32],
    'dropout_rate': 0.1,
    'learning_rate': 0.001,
    'weight_decay': 1e-5,
    'batch_size': 8,
    'epochs': 1000,
    'patience': 100,
    'clip_grad_norm': 1.0
}

# Создание датасета и загрузчика
train_dataset = PriceDataset(X_train_scaled, y_train)
test_dataset = PriceDataset(X_test_scaled, y_test)

train_loader = DataLoader(train_dataset, batch_size=params['batch_size'], shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=params['batch_size'], shuffle=False)

# Инициализация модели
input_dim = X_train_scaled.shape[1]
improved_model = ImprovedPricePredictor(
    input_dim=input_dim,
    hidden_dims=params['hidden_dims'],
    dropout_rate=params['dropout_rate']
)

print(f"Архитектура модели:")
print(f"  Входной слой: {input_dim} нейронов")
print(f"  Скрытые слои: {params['hidden_dims']}")
print(f"  Параметров: {sum(p.numel() for p in improved_model.parameters()):,}")

# Loss и оптимизатор
criterion = nn.MSELoss()
optimizer = optim.AdamW(
    improved_model.parameters(),
    lr=params['learning_rate'],
    weight_decay=params['weight_decay']
)

# Scheduler с плато
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='min',
    factor=0.5,
    patience=20,
    min_lr=1e-6,
)

# Обучение
history = train_pytorch_model(
    improved_model,
    train_loader,
    test_loader,
    criterion,
    optimizer,
    scheduler,
    epochs=params['epochs'],
    patience=params['patience'],
    clip_grad_norm=params['clip_grad_norm']
)

print(f"\nЛучшая модель достигла R² = {history['best_test_r2']:.4f}")

# ============================================
# ОЦЕНКА PyTorch МОДЕЛИ
# ============================================

# Получение предсказания
improved_model.eval()
with torch.no_grad():
    train_pred_log = improved_model(torch.FloatTensor(X_train_scaled)).numpy().flatten()
    test_pred_log = improved_model(torch.FloatTensor(X_test_scaled)).numpy().flatten()

# Метрики
train_metrics = evaluate_model_rub(y_train, train_pred_log)
test_metrics = evaluate_model_rub(y_test, test_pred_log)

print(f"\n📊 Результаты улучшенной PyTorch модели:")
print(f"  Train R² = {train_metrics['r2']:.4f}, MAPE = {train_metrics['mape']:.2f}%")
print(f"  Test  R² = {test_metrics['r2']:.4f}, MAPE = {test_metrics['mape']:.2f}%")

# ============================================
# 10. Добавление PyTorch в сравнение
# ============================================

# Добавление результатов PyTorch в all_results
all_results['PyTorch'] = test_metrics

# Создание ОБНОВЛЕННОГО comparison_df
comparison_df = pd.DataFrame(all_results).T
comparison_df = comparison_df.sort_values('r2', ascending=False)

print("\n" + "="*60)
print("ОБНОВЛЕННОЕ СРАВНЕНИЕ ВСЕХ МОДЕЛЕЙ (с PyTorch)")
print("="*60)
print(comparison_df.round(4).to_string())

# Обновленная визуализация
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# R² сравнение
axes[0].barh(comparison_df.index, comparison_df['r2'])
axes[0].set_xlabel('R² Score')
axes[0].set_title('Сравнение моделей по R²')
axes[0].grid(True, axis='x')

# MAE сравнение
axes[1].barh(comparison_df.index, comparison_df['mae'])
axes[1].set_xlabel('MAE (руб)')
axes[1].set_title('Сравнение моделей по MAE')
axes[1].grid(True, axis='x')

# MAPE сравнение
axes[2].barh(comparison_df.index, comparison_df['mape'])
axes[2].set_xlabel('MAPE (%)')
axes[2].set_title('Сравнение моделей по MAPE')
axes[2].grid(True, axis='x')

plt.tight_layout()
plt.show()

# Новая лучшая модель
best_model_name = comparison_df.index[0]
print(f"\nЛучшая модель: {best_model_name} с R² = {comparison_df.iloc[0]['r2']:.4f}")

# ============================================
# 11. Визуализация обучения PyTorch
# ============================================

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Loss график
axes[0,0].plot(history['train_losses'], label='Train Loss', alpha=0.7)
axes[0,0].plot(history['test_losses'], label='Test Loss', alpha=0.7)
axes[0,0].set_xlabel('Epoch')
axes[0,0].set_ylabel('Loss')
axes[0,0].set_title('Training History (Loss)')
axes[0,0].legend()
axes[0,0].grid(True, alpha=0.3)
axes[0,0].set_yscale('log')

# R² график
axes[0,1].plot(history['train_r2'], label='Train R²', alpha=0.7)
axes[0,1].plot(history['test_r2'], label='Test R²', alpha=0.7)
if 'XGBoost' in comparison_df.index:
    xgb_r2 = comparison_df.loc['XGBoost']['r2']
    axes[0,1].axhline(y=xgb_r2, color='r', linestyle='--',
                      label=f"XGBoost R²={xgb_r2:.3f}")
axes[0,1].set_xlabel('Epoch')
axes[0,1].set_ylabel('R² Score')
axes[0,1].set_title('Training History (R²)')
axes[0,1].legend()
axes[0,1].grid(True, alpha=0.3)

# Predicted vs Actual
axes[1,0].scatter(np.expm1(y_test), np.expm1(test_pred_log), alpha=0.6, s=50)
min_price = min(np.expm1(y_test).min(), np.expm1(test_pred_log).min())
max_price = max(np.expm1(y_test).max(), np.expm1(test_pred_log).max())
axes[1,0].plot([min_price, max_price], [min_price, max_price], 'r--', alpha=0.5)
axes[1,0].set_xlabel('Фактическая цена (руб)')
axes[1,0].set_ylabel('Предсказанная цена (руб)')
axes[1,0].set_title(f'PyTorch: Predicted vs Actual (R²={test_metrics["r2"]:.3f})')
axes[1,0].grid(True, alpha=0.3)

# Остатки
residuals = np.expm1(y_test) - np.expm1(test_pred_log)
axes[1,1].hist(residuals, bins=15, edgecolor='black', alpha=0.7)
axes[1,1].axvline(x=0, color='r', linestyle='--')
axes[1,1].axvline(x=residuals.mean(), color='g', linestyle=':', label=f'Mean: {residuals.mean():.0f}')
axes[1,1].set_xlabel('Остатки (руб)')
axes[1,1].set_ylabel('Частота')
axes[1,1].set_title('Распределение остатков')
axes[1,1].legend()
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## #10. Анализ остатков лучшей модели"""

print("\n" + "="*60)
print("10. АНАЛИЗ ОСТАТКОВ ЛУЧШЕЙ МОДЕЛИ")
print("="*60)

# Получение лучшей модели
best_model_name = comparison_df.index[0]
print(f"\nАнализ лучшей модели: {best_model_name} с R² = {comparison_df.iloc[0]['r2']:.4f}")

# Определение, какая модель лучшая и получение предсказания
if best_model_name == 'PyTorch':
    # Для PyTorch модели
    best_model = improved_model
    best_model.eval()
    with torch.no_grad():
        X_all_tensor = torch.FloatTensor(scaler.transform(X))
        y_pred_all_log = best_model(X_all_tensor).numpy().flatten()
    use_scaled = True
    model_type = 'pytorch'
else:
    # Для sklearn моделей - поиск в trained_models
    # Предварительное создание trained_models словаря, в случае отсутствия
    trained_models = {}

    # Переобучение всех моделей для сохранения
    print("\nПодготовка моделей для анализа...")
    for config in models_config:
        print(f"  Сохраняем {config['name']}...")
        if config['use_scaled']:
            X_tr, X_te = X_train_scaled, X_test_scaled
        else:
            X_tr, X_te = X_train.values, X_test.values

        model = config['model']
        model.fit(X_tr, y_train)
        trained_models[config['name']] = {
            'model': model,
            'use_scaled': config['use_scaled']
        }

    best_model_info = trained_models[best_model_name]
    best_model = best_model_info['model']

    if best_model_info['use_scaled']:
        X_all = scaler.transform(X)
    else:
        X_all = X.values

    y_pred_all_log = best_model.predict(X_all)
    model_type = 'sklearn'

# Конвертация обратно в рубли
y_pred_all_rub = np.expm1(y_pred_all_log)
y_all_rub = np.expm1(y)
residuals = y_all_rub - y_pred_all_rub
residuals_percent = (residuals / y_all_rub) * 100

# Статистика остатков
print("\nСТАТИСТИКА ОСТАТКОВ:")
print(f"  Среднее остатков: {residuals.mean():,.0f} руб")
print(f"  Медиана остатков: {np.median(residuals):,.0f} руб")
print(f"  Std остатков: {residuals.std():,.0f} руб")
print(f"  Min остаток: {residuals.min():,.0f} руб")
print(f"  Max остаток: {residuals.max():,.0f} руб")
print(f"  Доля остатков в пределах 1σ: {((np.abs(residuals) < residuals.std()).sum() / len(residuals) * 100):.1f}%")
print(f"  Доля остатков в пределах 2σ: {((np.abs(residuals) < 2*residuals.std()).sum() / len(residuals) * 100):.1f}%")

print(f"\nСТАТИСТИКА ОТНОСИТЕЛЬНЫХ ОСТАТКОВ:")
print(f"  Средняя абсолютная ошибка (MAPE): {np.mean(np.abs(residuals_percent)):.2f}%")
print(f"  Медианная абсолютная ошибка: {np.median(np.abs(residuals_percent)):.2f}%")
print(f"  Min относительная ошибка: {residuals_percent.min():.2f}%")
print(f"  Max относительная ошибка: {residuals_percent.max():.2f}%")

# Визуализация остатков
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# 1. Predicted vs Actual
axes[0, 0].scatter(y_all_rub, y_pred_all_rub, alpha=0.6, s=50, edgecolors='black')
axes[0, 0].plot([y_all_rub.min(), y_all_rub.max()],
                [y_all_rub.min(), y_all_rub.max()], 'r--', lw=2, label='Идеальная линия')
axes[0, 0].set_xlabel('Фактическая цена (руб)')
axes[0, 0].set_ylabel('Предсказанная цена (руб)')
axes[0, 0].set_title(f'{best_model_name}: Predicted vs Actual\nR² = {comparison_df.iloc[0]["r2"]:.4f}')
axes[0, 0].grid(True, alpha=0.3)
axes[0, 0].legend()

# 2. Распределение остатков (гистограмма)
axes[0, 1].hist(residuals, bins=20, edgecolor='black', alpha=0.7, color='skyblue')
axes[0, 1].axvline(x=0, color='r', linestyle='--', linewidth=2, label='0')
axes[0, 1].axvline(x=residuals.mean(), color='g', linestyle=':', linewidth=2,
                    label=f'Среднее: {residuals.mean():,.0f}')
axes[0, 1].axvline(x=residuals.mean() + residuals.std(), color='orange', linestyle=':',
                    linewidth=1.5, alpha=0.7, label=f'±1σ: {residuals.std():,.0f}')
axes[0, 1].axvline(x=residuals.mean() - residuals.std(), color='orange', linestyle=':',
                    linewidth=1.5, alpha=0.7)
axes[0, 1].set_xlabel('Остатки (руб)')
axes[0, 1].set_ylabel('Частота')
axes[0, 1].set_title('Распределение остатков')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# 3. Q-Q plot
from scipy import stats
stats.probplot(residuals, dist="norm", plot=axes[0, 2])
axes[0, 2].set_title('Q-Q plot остатков\n(Проверка на нормальность)')
axes[0, 2].grid(True, alpha=0.3)

# 4. Остатки vs Предсказания
axes[1, 0].scatter(y_pred_all_rub, residuals, alpha=0.6, s=50, edgecolors='black')
axes[1, 0].axhline(y=0, color='r', linestyle='--', linewidth=2)
axes[1, 0].axhline(y=residuals.mean(), color='g', linestyle=':',
                    label=f'Среднее: {residuals.mean():,.0f}')
axes[1, 0].fill_between([y_pred_all_rub.min(), y_pred_all_rub.max()],
                         [-residuals.std(), -residuals.std()],
                         [residuals.std(), residuals.std()],
                         alpha=0.2, color='orange', label='±1σ')
axes[1, 0].set_xlabel('Предсказанная цена (руб)')
axes[1, 0].set_ylabel('Остатки (руб)')
axes[1, 0].set_title('Остатки vs Предсказания\n(Проверка на гетероскедастичность)')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

# 5. Относительные остатки
axes[1, 1].scatter(y_pred_all_rub, residuals_percent, alpha=0.6, s=50, edgecolors='black')
axes[1, 1].axhline(y=0, color='r', linestyle='--', linewidth=2)
axes[1, 1].axhline(y=residuals_percent.mean(), color='g', linestyle=':',
                    label=f'Среднее: {residuals_percent.mean():.1f}%')
axes[1, 1].fill_between([y_pred_all_rub.min(), y_pred_all_rub.max()],
                         [-np.std(residuals_percent), -np.std(residuals_percent)],
                         [np.std(residuals_percent), np.std(residuals_percent)],
                         alpha=0.2, color='orange', label=f'±1σ: {np.std(residuals_percent):.1f}%')
axes[1, 1].set_xlabel('Предсказанная цена (руб)')
axes[1, 1].set_ylabel('Относительные остатки (%)')
axes[1, 1].set_title('Относительные остатки vs Предсказания')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

# 6. Boxplot остатков по ценовым сегментам
# Создаем ценовые сегменты
price_segments = pd.cut(y_all_rub, bins=[0, 1e6, 2e6, 3e6, 5e6, 10e6, 40e6],
                         labels=['<1M', '1-2M', '2-3M', '3-5M', '5-10M', '>10M'])
residuals_df = pd.DataFrame({'residuals': residuals, 'segment': price_segments})
residuals_df.boxplot(column='residuals', by='segment', ax=axes[1, 2])
axes[1, 2].set_title('Распределение остатков по ценовым сегментам')
axes[1, 2].set_xlabel('Ценовой сегмент')
axes[1, 2].set_ylabel('Остатки (руб)')
axes[1, 2].grid(True, alpha=0.3)

plt.suptitle(f'Анализ остатков модели {best_model_name}', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

# Дополнительный анализ: поиск выбросов
z_scores = np.abs((residuals - residuals.mean()) / residuals.std())
outliers = z_scores > 2

print(f"\nАНАЛИЗ ВЫБРОСОВ:")
print(f"  Количество выбросов (|z|>2): {outliers.sum()} из {len(residuals)} ({outliers.sum()/len(residuals)*100:.1f}%)")

if outliers.sum() > 0:
    print("\n  Топ-5 наибольших выбросов:")
    outlier_indices = np.argsort(np.abs(residuals))[-5:][::-1]
    for idx in outlier_indices:
        print(f"    {df.iloc[idx]['model']}, {df.iloc[idx]['year']} г.: "
              f"факт={df.iloc[idx]['price']:,.0f} руб, "
              f"прогноз={y_pred_all_rub[idx]:,.0f} руб, "
              f"ошибка={residuals[idx]:+,.0f} руб ({residuals_percent[idx]:+.1f}%)")

"""## #11. Сохранение лучшей модели для Streamlit приложения"""

print("\n" + "="*60)
print("11. СОХРАНЕНИЕ ЛУЧШЕЙ МОДЕЛИ ДЛЯ STREAMLIT")
print("="*60)

import pickle
import joblib
import json
from datetime import datetime

# Создание директории для сохранения моделей, на случай её отсутствия
import os
os.makedirs('saved_models', exist_ok=True)

# Информация о лучшей модели
best_model_info = {
    'model_name': best_model_name,
    'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'metrics': comparison_df.loc[best_model_name].to_dict(),
    'features': existing_features,
    'n_features': len(existing_features),
    'data_size': len(df),
    'feature_importance': None
}

# Сохранение модели в зависимости от типа
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

if best_model_name == 'PyTorch':
    # Для PyTorch модели
    model_path = f'saved_models/best_pytorch_model_{timestamp}.pth'
    torch.save(improved_model.state_dict(), model_path)

    # Сохранение архитектуры модели
    model_architecture = {
        'type': 'ImprovedPricePredictor',
        'input_dim': input_dim,
        'hidden_dims': params['hidden_dims'],
        'dropout_rate': params['dropout_rate']
    }

    best_model_info['model_path'] = model_path
    best_model_info['model_type'] = 'pytorch'
    best_model_info['architecture'] = model_architecture

    print(f"PyTorch модель сохранена: {model_path}")

elif best_model_name in ['RandomForest', 'GradientBoosting', 'XGBoost', 'CatBoost']:
    # Для больших моделей используется joblib
    model_path = f'saved_models/best_{best_model_name.lower()}_{timestamp}.joblib'
    joblib.dump(best_model, model_path)

    # Важность признаков
    if hasattr(best_model, 'feature_importances_'):
        best_model_info['feature_importance'] = dict(zip(
            existing_features,
            best_model.feature_importances_.tolist()
        ))

    best_model_info['model_path'] = model_path
    best_model_info['model_type'] = 'joblib'

    print(f"Joblib модель сохранена: {model_path}")

else:
    # Для простых sklearn моделей
    model_path = f'saved_models/best_{best_model_name.lower()}_{timestamp}.pkl'
    with open(model_path, 'wb') as f:
        pickle.dump(best_model, f)

    # Коэффициенты для линейных моделей
    if hasattr(best_model, 'coef_'):
        best_model_info['coefficients'] = dict(zip(
            existing_features,
            best_model.coef_.flatten().tolist() if len(best_model.coef_.shape) > 1 else best_model.coef_.tolist()
        ))

    best_model_info['model_path'] = model_path
    best_model_info['model_type'] = 'pickle'

    print(f"Pickle модель сохранена: {model_path}")

# Сохранение scaler
scaler_path = f'saved_models/scaler_{timestamp}.pkl'
with open(scaler_path, 'wb') as f:
    pickle.dump(scaler, f)
best_model_info['scaler_path'] = scaler_path
print(f"📏 Scaler сохранен: {scaler_path}")

# Сохранение статистики моделей
if 'model_stats' in locals():
    stats_path = f'saved_models/model_stats_{timestamp}.pkl'
    with open(stats_path, 'wb') as f:
        pickle.dump(model_stats.to_dict(), f)
    best_model_info['model_stats_path'] = stats_path

# Сохранение метаданных и конфигурации
config_path = f'saved_models/model_config_{timestamp}.json'
with open(config_path, 'w', encoding='utf-8') as f:
    # Конвертация
    config_serializable = {}
    for k, v in best_model_info.items():
        if isinstance(v, dict):
            config_serializable[k] = {kk: float(vv) if isinstance(vv, (np.float32, np.float64)) else vv
                                      for kk, vv in v.items()}
        elif isinstance(v, (np.float32, np.float64)):
            config_serializable[k] = float(v)
        elif isinstance(v, np.int64):
            config_serializable[k] = int(v)
        else:
            config_serializable[k] = v
    json.dump(config_serializable, f, indent=2, ensure_ascii=False)

print(f"Конфигурация сохранена: {config_path}")

# Сохранение полного пайплайна для Streamlit
pipeline = {
    'model_name': best_model_name,
    'model_path': model_path,
    'scaler_path': scaler_path,
    'features': existing_features,
    'model_type': best_model_info['model_type'],
    'metrics': best_model_info['metrics'],
    'feature_importance': best_model_info.get('feature_importance'),
    'model_stats': model_stats.to_dict() if 'model_stats' in locals() else None
}

# Для PyTorch модели добавление архитектуры
if best_model_name == 'Improved_PyTorch':
    pipeline['architecture'] = model_architecture

pipeline_path = f'saved_models/full_pipeline_{timestamp}.pkl'
with open(pipeline_path, 'wb') as f:
    pickle.dump(pipeline, f)

print(f"Полный пайплайн сохранен: {pipeline_path}")

# Создание упрощенной версии для быстрой загрузки в Streamlit
simple_pipeline = {
    'model_name': best_model_name,
    'model_path': model_path,
    'scaler_path': scaler_path,
    'features': existing_features,
    'model_type': best_model_info['model_type'],
    'feature_names': [f.replace('_', ' ').title() for f in existing_features]
}

simple_path = f'saved_models/streamlit_model_{timestamp}.pkl'
with open(simple_path, 'wb') as f:
    pickle.dump(simple_pipeline, f)

print(f"Streamlit-совместимая модель сохранена: {simple_path}")

# Сохраняем comparison_df для истории
comparison_path = f'saved_models/model_comparison_{timestamp}.csv'
comparison_df.to_csv(comparison_path)
print(f"Сравнение моделей сохранено: {comparison_path}")

# Финальный отчет
print("\n" + "="*60)
print("СОХРАНЕНИЕ ЗАВЕРШЕНО")
print("="*60)
print(f"\nЛучшая модель: {best_model_name}")
print(f"R² = {comparison_df.loc[best_model_name]['r2']:.4f}")
print(f"MAPE = {comparison_df.loc[best_model_name]['mape']:.2f}%")
print(f"MAE = {comparison_df.loc[best_model_name]['mae']:,.0f} руб")